// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeGPZTifHhNe6Xwxc6DZcZGtQaaRxl2Gw',
    appId: '1:441282518340:web:7678c1036a31adcd960b11',
    messagingSenderId: '441282518340',
    projectId: 'contactapp-1b3dc',
    authDomain: 'contactapp-1b3dc.firebaseapp.com',
    storageBucket: 'contactapp-1b3dc.firebasestorage.app',
    measurementId: 'G-WBS6TCYLR6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcRQ36NywBw74u2JSXBCt9V0WNRhX_jwA',
    appId: '1:441282518340:android:16afeceaf29ba154960b11',
    messagingSenderId: '441282518340',
    projectId: 'contactapp-1b3dc',
    storageBucket: 'contactapp-1b3dc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsRPRtw_j19XkriJM18Kr_hQGweEFJdBw',
    appId: '1:441282518340:ios:932540d7ed3c195e960b11',
    messagingSenderId: '441282518340',
    projectId: 'contactapp-1b3dc',
    storageBucket: 'contactapp-1b3dc.firebasestorage.app',
    iosBundleId: 'com.learn.contactapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsRPRtw_j19XkriJM18Kr_hQGweEFJdBw',
    appId: '1:441282518340:ios:932540d7ed3c195e960b11',
    messagingSenderId: '441282518340',
    projectId: 'contactapp-1b3dc',
    storageBucket: 'contactapp-1b3dc.firebasestorage.app',
    iosBundleId: 'com.learn.contactapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDeGPZTifHhNe6Xwxc6DZcZGtQaaRxl2Gw',
    appId: '1:441282518340:web:992f7f8ab2692bde960b11',
    messagingSenderId: '441282518340',
    projectId: 'contactapp-1b3dc',
    authDomain: 'contactapp-1b3dc.firebaseapp.com',
    storageBucket: 'contactapp-1b3dc.firebasestorage.app',
    measurementId: 'G-6GR8C939GW',
  );
}
