// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXNpJpFtF9TLj0y6pjC4pLKW_Y6uzryzA',
    appId: '1:566465789964:web:c66d364689f96e2e452e29',
    messagingSenderId: '566465789964',
    projectId: 'fashions-ecom',
    authDomain: 'fashions-ecom.firebaseapp.com',
    storageBucket: 'fashions-ecom.firebasestorage.app',
    measurementId: 'G-WJ9MDX8QW8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeJCqfCduR0iX-tEkNQgscfpoLwmHPQLU',
    appId: '1:566465789964:android:657f0637b2a6e23d452e29',
    messagingSenderId: '566465789964',
    projectId: 'fashions-ecom',
    storageBucket: 'fashions-ecom.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB81lNhDDEWd6JDzH8sHX97pZnU6L1f5vA',
    appId: '1:566465789964:ios:53d9fbdb99d12e45452e29',
    messagingSenderId: '566465789964',
    projectId: 'fashions-ecom',
    storageBucket: 'fashions-ecom.firebasestorage.app',
    iosBundleId: 'com.project.fashionsEcom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB81lNhDDEWd6JDzH8sHX97pZnU6L1f5vA',
    appId: '1:566465789964:ios:53d9fbdb99d12e45452e29',
    messagingSenderId: '566465789964',
    projectId: 'fashions-ecom',
    storageBucket: 'fashions-ecom.firebasestorage.app',
    iosBundleId: 'com.project.fashionsEcom',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXNpJpFtF9TLj0y6pjC4pLKW_Y6uzryzA',
    appId: '1:566465789964:web:33f14b3856c8f1b2452e29',
    messagingSenderId: '566465789964',
    projectId: 'fashions-ecom',
    authDomain: 'fashions-ecom.firebaseapp.com',
    storageBucket: 'fashions-ecom.firebasestorage.app',
    measurementId: 'G-PRCCRFQ5TN',
  );
}
